title: "Ludovic Thérage"
email: "ludovictherage2@gmail.com"
description: "Portfolio de Ludovic Thérage - développeur / étudiant en informatique"
baseurl: "/Portfolio"   # nom exact du repo
url: "https://ltherage.github.io"
markdown: kramdown
theme: minima
plugins: []
